application:
  host: http://localhost:8080
  public-urls:
    - /swagger-ui/**
    - /swagger-ui.html
    - /v3/api-docs/**
    - /csrf
    - /
    - /webjars/**
    - /swagger-resources/**
    - /environnement
    - /healthcheck
    - /actuator/**
  roles:
    interviewer:
    reviewer:
    admin:
    webclient:
    reviewer-alternative:
  auth:  # KEYCLOAK | NOAUTH
  ## if KEYCLOAK enabled
  security:
    # if keycloak auth enabled
    keycloak:
      auth-server-host: https://auth-server.host
      auth-server-url: ${application.security.keycloak.auth-server-host}/auth
      client-id: my-client-id
      realm: my-realm
      principal-attribute: principal-attribute
      additional-realm: additional-realm
  corsOrigins:
  # Folder where to store temp files.
  # DO NOT USE THE DEFAULT TEMP DIRECTORY OF THE OS as it adresses some vulnerabilities.
  # Use a folder with permissions for the app only
  temp-folder:
  # Pearljam-bo url
  pilotage:
    service:
      url:
        scheme:
        host:
        port:
    #alternative habilitation
    alternative-habilitation-service:
      url: http://alternative.url
      campaignids-regex: ((edt)|(EDT))(\d|\S){1,}
    #If true, checkHabilitation and getSuFromPilotage are not used to secure the endpoints
    integration-override: false
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 2
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      id:
        new_generator_mappings: true
      cache:
        use_second_level_cache: false
        use_query_cache: false
      generate_statistics: false
      hbm2ddl:
        auto: validate
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${application.security.keycloak.auth-server-url}/realms/${application.security.keycloak.realm}

  liquibase:
    enabled: true
    contexts: prod
    defaultSchema: public
    change-log: classpath:db/master.xml
  profiles:
    group:
      cache-testing: test,test-cache

springdoc:
  swagger-ui:
    oauth:
      client-id: ${application.security.keycloak.client-id}
      oauth2RedirectUrl: ${application.host}/swagger-ui/oauth2-redirect.html
    path: /
    syntax-highlight:
      activated: false
    tagsSorter: alpha
    doc-expansion: none

#Actuator Metrics
management:
  endpoints:
    enabled-by-default: false
    metrics:
      enabled: true
    prometheus:
      enabled: true
    web:
      exposure:
        include: metrics,prometheus

logging:
  level:
    root: INFO
    liquibase: ERROR
  logback:
    rollingpolicy:
      max-history: 90

feature:
  enableSwagger: true