application:
  public-urls:
    - /swagger-ui/**
    - /v3/api-docs/**
    - /api/healthcheck
    - /actuator/**
    - /
  roles:
    interviewer:
    reviewer:
    admin:
    webclient:
    reviewer-alternative:
  auth:  # OIDC | NOAUTH
  ## if OIDC enabled
  security:
    oidc:
      auth-server-host: https://auth-server.host
      auth-server-url: ${application.security.oidc.auth-server-host}/auth
      client-id: my-client-id
      realm: my-realm
      principal-attribute: id-claim
      role-claim: role-claim
  corsOrigins:
  # Folder where to store temp files.
  # DO NOT USE THE DEFAULT TEMP DIRECTORY OF THE OS as it adresses some vulnerabilities.
  # Use a folder with permissions for the app only
  temp-folder:
  # Pearljam-bo url
  pilotage:
    url:
    #alternative habilitation
    alternative-habilitation:
      url: http://alternative.url
      campaignids-regex: ((edt)|(EDT))(\d|\S){1,}
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 2
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      id:
        new_generator_mappings: true
      cache:
        use_second_level_cache: false
        use_query_cache: false
      generate_statistics: false
      hbm2ddl:
        auto: validate
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${application.security.oidc.auth-server-url}/realms/${application.security.oidc.realm}

  liquibase:
    enabled: true
    contexts: prod
    defaultSchema: public
    change-log: classpath:db/master.xml
  profiles:
    group:
      cache-testing: test,test-cache

springdoc:
  swagger-ui:
    oauth:
      client-id: ${application.security.oidc.client-id}
      # /!\ when injecting this property from env var, cannot convert KCIDPHINT env var to kc_idp_hint otherwise
      # This property is a hint for spring-boot to map the env var to this property
      additionalQueryStringParams:
        kc_idp_hint: my-idp
    path: /
    syntax-highlight:
      activated: false
    tagsSorter: alpha
    doc-expansion: none
#Actuator Metrics
management:
  endpoints:
    enabled-by-default: false
    metrics:
      enabled: true
    prometheus:
      enabled: true
    web:
      exposure:
        include: metrics,prometheus

logging:
  level:
    root: INFO
    liquibase: ERROR
  pattern:
    console: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%X{id}][%X{user}][%X{method} %X{path}] [%thread] %-5level %logger{36} - %htmlEncode{%m}%n"
    file: ${logging.pattern.console}
  logback:
    rollingpolicy:
      max-history: 90
feature:
  enable:
    dataset: false
    swagger: false
    pilotage: true
    cache: true
    comments: false