# podman-compose -f ./compose.yml --env-file .env --profile keycloak --profile activemq --profile sabiane-questionnaire-db --profile sabiane-questionnaire-api --profile sabiane-pilotage-db --profile sabiane-pilotage-api down -v

services:
  keycloak:
    extends:
      file: ./container/compose.keycloak.yml
      service: keycloak
    profiles:
      - all
      - keycloak

  activemq:
    extends:
      file: ./container/compose.activemq.yml
      service: activemq
    profiles:
      - all
      - activemq

  sabiane-questionnaire-db:
    extends:
      file: ./container/compose.sabiane-questionnaire-db.yml
      service: sabiane-questionnaire-db
    profiles:
      - all
      - sabiane-questionnaire-db

  sabiane-pilotage-db:
    extends:
      file: ./container/compose.sabiane-pilotage-db.yml
      service: sabiane-pilotage-db
    profiles:
      - all
      - sabiane-pilotage-db

  sabiane-pilotage-api:
    extends:
      file: ./container/compose.sabiane-pilotage-api.yml
      service: sabiane-pilotage-api
    profiles:
      - all
      - sabiane-pilotage-api

  sabiane-questionnaire-api:
    extends:
      file: ./container/compose.sabiane-questionnaire-api.yml
      service: sabiane-questionnaire-api
    depends_on:
      sabiane-questionnaire-db:
        condition: service_healthy
      keycloak:
        condition: service_started
#    restart: on-failure
    profiles:
      - all
      - sabiane-questionnaire-api

volumes:
  activemq_vol:
