# podman-compose -f ./compose.yml --env-file .env --profile keycloak --profile activemq --profile sabiane-questionnaire-db --profile sabiane-questionnaire-api --profile sabiane-pilotage-db --profile sabiane-pilotage-api --profile questionnaire-enqueteur-ui down -v

services:

# ┌──────────────────────────────────────────┐
# │         Services transverses             │
# └──────────────────────────────────────────┘

  keycloak:
    extends:
      file: ./container/compose.keycloak.yml
      service: keycloak
    profiles:
      - all
      - transverse
      - keycloak

  activemq:
    extends:
      file: ./container/compose.activemq.yml
      service: activemq
    profiles:
      - all
      - transverse
      - activemq

# ┌─────────────────────────────────────────────────┐
# │         Sabiane - Collecte enquêteurs           │
# └─────────────────────────────────────────────────┘

  sabiane-questionnaire-db:
    extends:
      file: ./container/compose.sabiane-questionnaire-db.yml
      service: sabiane-questionnaire-db
    profiles:
      - all
      - sabiane
      - sabiane-questionnaire-db

  sabiane-pilotage-db:
    extends:
      file: ./container/compose.sabiane-pilotage-db.yml
      service: sabiane-pilotage-db
    profiles:
      - all
      - sabiane
      - sabiane-pilotage-db

  sabiane-pilotage-api:
    extends:
      file: ./container/compose.sabiane-pilotage-api.yml
      service: sabiane-pilotage-api
    depends_on:
      sabiane-pilotage-db:
        condition: service_healthy
      keycloak:
        condition: service_started
    profiles:
      - all
      - sabiane
      - sabiane-pilotage-api

  sabiane-questionnaire-api:
    extends:
      file: ./container/compose.sabiane-questionnaire-api.yml
      service: sabiane-questionnaire-api
    depends_on:
      sabiane-questionnaire-db:
        condition: service_healthy
      keycloak:
        condition: service_started
#    restart: on-failure
    profiles:
      - all
      - sabiane
      - sabiane-questionnaire-api

  questionnaire-enqueteur-ui:
    extends:
      file: ./container/compose.sabiane-questionnaire-enqueteur-ui.yml
      service: questionnaire-enqueteur-ui
    depends_on:
      keycloak:
        condition: service_started
      sabiane-questionnaire-api:
        condition: service_started
    profiles:
      - all
      - sabiane
      - questionnaire-enqueteur-ui

  sabiane-collecte-ui:
    extends:
      file: ./container/compose.sabiane-collecte-ui.yml
      service: sabiane-collecte-ui
    depends_on:
      questionnaire-enqueteur-ui:
        condition: service_started
      keycloak:
        condition: service_started
      sabiane-pilotage-api:
        condition: service_started
    profiles:
      - all
      - sabiane
      - sabiane-collecte-ui

# ┌──────────────────────────────────────────┐
# │         Platine - Collecte WEB           │
# └──────────────────────────────────────────┘

  platine-questionnaire-db:
    extends:
      file: ./container/compose.platine-questionnaire-db.yml
      service: platine-questionnaire-db
    profiles:
      - all
      - platine
      - platine-questionnaire-db

  platine-questionnaire-api:
    extends:
      file: ./container/compose.platine-questionnaire-api.yml
      service: platine-questionnaire-api
    depends_on:
      platine-questionnaire-db:
        condition: service_healthy
      keycloak:
        condition: service_started
    #    restart: on-failure
    profiles:
      - all
      - platine
      - platine-questionnaire-api

# ┌──────────────────────────────────────────┐
# │         Volumes                          │
# └──────────────────────────────────────────┘

volumes:
  activemq_vol:
