services:
  sabiane-questionnaire-api:
#    build:
#      context: ../
#      dockerfile: Dockerfile
    image: ${IMAGES_REGISTRY_DOCKER_IO}/${IMAGE_SABIANE_QUESTIONNAIRE_API}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sabiane-questionnaire-db:5432/${QUESTIONNAIRE_SABIANE_DB}
      - SPRING_DATASOURCE_USERNAME=${QUESTIONNAIRE_SABIANE_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${QUESTIONNAIRE_SABIANE_DB_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - APPLICATION_ROLES_SURVEYUNIT=${RESPONDENT_ROLE}
      - APPLICATION_ROLES_REVIEWER=${INTERNAL_USER_ROLE}
      - APPLICATION_ROLES_ADMIN=${ADMIN_ROLE}
      - APPLICATION_ROLES_WEBCLIENT=${WEBCLIENT_ROLE}
      - FEATURE_OIDC_ENABLED=true
      - FEATURE_OIDC_REALM=${AUTH_REALM_SABIANE}
      - FEATURE_OIDC_CLIENTID=${AUTH_CLIENT_ID}
      - FEATURE_OIDC_AUTHSERVERHOST=${AUTH_SERVER_URL}
      - FEATURE_OIDC_AUTHSERVERURL=${AUTH_SERVER_URL}
      - FEATURE_OIDC_ROLECLAIM=${JWT_ROLE_CLAIM}
      - FEATURE_OIDC_PRINCIPALATTRIBUTE=preferred_username
      - SPRINGDOC_SWAGGERUI_OAUTH_ADDITIONALQUERYSTRINGPARAMS_KC_IDP_HINT=${IDP_HINT}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=${AUTH_SERVER_URL}/realms/${AUTH_REALM}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI=http://keycloak:8080/realms/${AUTH_REALM}/protocol/openid-connect/certs
      - APPLICATION_ROLES_INTERVIEWER=interviewer
      - APPLICATION_ROLES_REVIEWER=gestionnaire
      - APPLICATION_ROLES_ADMIN=admin
      - APPLICATION_ROLES_WEBCLIENT=webclient
      - APPLICATION_CORSORIGINS=http://localhost:3000,http://localhost:5001
      - FEATURE_SWAGGER_ENABLED=true
      - FEATURE_INTERVIEWER_MODE_ENABLED=true
#      TODO ?
      - FEATURE_PILOTAGE_ENABLED=true
      - FEATURE_PILOTAGE_URL=http://sabiane-pilotage-api:8080
      - SPRING_LIQUIBASE_ENABLED=true
      - SPRING_LIQUIBASE_CONTEXTS=demo
      - SPRING_LIQUIBASE_CHANGE_LOG=classpath:db/integration-demo.xml
      - APPLICATION_TEMP_FOLDER=/opt/app/temp-files
      - FEATURE_CROSSENVIRONMENTCOMMUNICATION_EMITTER=true
      - FEATURE_CROSSENVIRONMENTCOMMUNICATION_CONSUMER=true
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
    depends_on:
      sabiane-questionnaire-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/api/healthcheck || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s
