services:
  queen-db-ciphered:
    image: postgres:14.15
    environment:
      - POSTGRES_USER=${QUEEN_DB_USER}
      - POSTGRES_PASSWORD=${QUEEN_DB_PASSWORD}
      - POSTGRES_DB=${QUEEN_DB_CIPHERED}
    command: ["postgres"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${QUEEN_DB_USER} -d ${QUEEN_DB_CIPHERED} -h localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - ${QUEEN_DB_CIPHERED_PORT}:5432