services:
  queen-db-remote:
    image: ${IMAGES_REGISTRY_DOCKER_IO}/${IMAGE_POSTGRES}
    environment:
      - POSTGRES_USER=queenremote
      - POSTGRES_PASSWORD=queenremote
      - POSTGRES_DB=queen-remote
    command: ["postgres"]
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U queenremote -d queen-remote -h localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "5436:5432"

  queen-remote:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      queen-db-remote:
        condition: service_healthy
      activemq:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://queen-db-remote:5432/queen-remote
      - SPRING_DATASOURCE_USERNAME=queenremote
      - SPRING_DATASOURCE_PASSWORD=queenremote
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - FEATURE_OIDC_ENABLED=false
      - FEATURE_PILOTAGE_ENABLED=false
      - FEATURE_SWAGGER_ENABLED=false
      - SPRING_LIQUIBASE_ENABLED=true
      - SPRING_LIQUIBASE_CONTEXTS=test
      - SPRING_LIQUIBASE_CHANGE_LOG=classpath:db/integration-test.xml
      - APPLICATION_CORSORIGINS=*
      - APPLICATION_TEMP_FOLDER=/opt/app/temp-files
      - FEATURE_CROSSENVIRONMENTCOMMUNICATION_EMITTER=true
      - FEATURE_CROSSENVIRONMENTCOMMUNICATION_CONSUMER=true
      - SPRING_ARTEMIS_BROKER_URL=tcp://activemq:61616
      - SPRING_ARTEMIS_USER=admin
      - SPRING_ARTEMIS_PASSWORD=admin
    ports:
      - "8081:8080"
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/api/healthcheck || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s

  queen-remote-init:
    image: ${IMAGES_REGISTRY_DOCKER_IO}/${IMAGE_POSTGRES}
    depends_on:
      queen-remote:
        condition: service_healthy
    volumes:
      - ./init-remote-data.sh:/init-remote-data.sh:ro
    command: ["bash", "/init-remote-data.sh"]
    restart: "no"
