services:
  queen-db:
    image: ${IMAGES_REGISTRY_DOCKER_IO}/${IMAGE_POSTGRES}
    environment:
      - POSTGRES_USER=${QUEEN_DB_USER}
      - POSTGRES_PASSWORD=${QUEEN_DB_PASSWORD}
      - POSTGRES_DB=${QUEEN_DB}
    command: ["postgres"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${QUEEN_DB_USER} -d ${QUEEN_DB} -h localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - ${QUEEN_DB_PORT}:5432